name: "Deploying To Production Environment"

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: tellihealth/gen-postman-documentation@1.0.1
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}"
          collection: "Production"
