name: "Deploying To Production Environment"

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout Repository"
      - uses: tellihealth/gen-postman-documentation@1.0.1
        name: "Generate Postman Documentation"
        with:
          api-key: ${{ secrets.POSTMAN_API_KEY }}
          collection: "Production"
          yml: "postman.yml"
